**cleaning all tables**

**Data definition**

In [1]:
import zipfile
import pandas as pd
import io


zip_file_path = "C:/Users/pc/Desktop/DEPI/final project/logistics-operations-database.zip"

logistics_tables = {}


with zipfile.ZipFile(zip_file_path, 'r') as archive:
   
    print("الملفات الموجودة جوه الـ zip:")
    print(archive.namelist())
    print("-" * 50)
    
    for file_path in archive.namelist():
        
        if file_path.endswith('.csv'):
            
            file_name = file_path.split('/')[-1].replace('.csv', '')
            
            with archive.open(file_path) as file:
                logistics_tables[file_name] = pd.read_csv(file)
                print(f"تم تحميل جدول [{file_name}] بنجاح! الأبعاد: {logistics_tables[file_name].shape}")

الملفات الموجودة جوه الـ zip:
['data/', 'data/customers.csv', 'data/DATABASE_SCHEMA.txt', 'data/delivery_events.csv', 'data/drivers.csv', 'data/driver_monthly_metrics.csv', 'data/facilities.csv', 'data/fuel_purchases.csv', 'data/loads.csv', 'data/maintenance_records.csv', 'data/routes.csv', 'data/safety_incidents.csv', 'data/trailers.csv', 'data/trips.csv', 'data/trucks.csv', 'data/truck_utilization_metrics.csv']
--------------------------------------------------
تم تحميل جدول [customers] بنجاح! الأبعاد: (200, 8)
تم تحميل جدول [delivery_events] بنجاح! الأبعاد: (170820, 11)
تم تحميل جدول [drivers] بنجاح! الأبعاد: (150, 12)
تم تحميل جدول [driver_monthly_metrics] بنجاح! الأبعاد: (4464, 9)
تم تحميل جدول [facilities] بنجاح! الأبعاد: (50, 9)
تم تحميل جدول [fuel_purchases] بنجاح! الأبعاد: (196442, 11)
تم تحميل جدول [loads] بنجاح! الأبعاد: (85410, 12)
تم تحميل جدول [maintenance_records] بنجاح! الأبعاد: (2920, 12)
تم تحميل جدول [routes] بنجاح! الأبعاد: (58, 9)
تم تحميل جدول [safety_incidents] بنجاح! الأبعاد: (170, 15)
تم تحميل جدول [trailers] بنجاح! الأبعاد: (180, 9)
تم تحميل جدول [trips] بنجاح! الأبعاد: (85410, 12)
تم تحميل جدول [trucks] بنجاح! الأبعاد: (120, 11)
تم تحميل جدول [truck_utilization_metrics] بنجاح! الأبعاد: (3312, 10)

In [2]:
customers= logistics_tables.get('customers')
delivery_events= logistics_tables.get('delivery_events')
driver_monthly_metrics= logistics_tables.get('driver_monthly_metrics')
drivers= logistics_tables.get('drivers')
facilities= logistics_tables.get('facilities')
fuel_purchases= logistics_tables.get('fuel_purchases')
loads= logistics_tables.get('loads')
maintenance_records= logistics_tables.get('maintenance_records')
routes= logistics_tables.get('routes')
safety_incidents= logistics_tables.get('safety_incidents')
trailers= logistics_tables.get('trailers')
trips= logistics_tables.get('trips')
truck_utilization_metrics= logistics_tables.get('truck_utilization_metrics')
trucks= logistics_tables.get('trucks')

In [3]:
print(customers.shape)
print(delivery_events.shape)
print(driver_monthly_metrics.shape)
print(drivers.shape)
print(facilities.shape)
print(fuel_purchases.shape)
print(loads.shape)
print(maintenance_records.shape)
print(routes.shape)
print(safety_incidents.shape)
print(trailers.shape)
print(trips.shape)
print(truck_utilization_metrics.shape)
print(trucks.shape)

(200, 8)
(170820, 11)
(4464, 9)
(150, 12)
(50, 9)
(196442, 11)
(85410, 12)
(2920, 12)
(58, 9)
(170, 15)
(180, 9)
(85410, 12)
(3312, 10)
(120, 11)

**1-Customers EDA and cleaning if it needs**

In [4]:
print("=== 1. معلومات الجدول وأنواع البيانات ===")
customers.info()

print("\n" + "="*40 + "\n")

print("=== 2. عدد الـ Nulls في كل عمود ===")
print(customers.isna().sum())

print("\n" + "="*40 + "\n")

print("=== 3. عدد الصفوف المكررة بالكامل ===")
print(f"Total Duplicates: {customers.duplicated().sum()}")

print("\n" + "="*40 + "\n")

print("=== 4. الإحصاءات الوصفية ===")
display(customers.describe(include='all'))

print("\n" + "="*40 + "\n")

print("=== 5. عينة من أول 5 صفوف ===")
display(customers.head())

=== 1. معلومات الجدول وأنواع البيانات ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    object
 1   customer_name             200 non-null    object
 2   customer_type             200 non-null    object
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    object
 5   account_status            200 non-null    object
 6   contract_start_date       200 non-null    object
 7   annual_revenue_potential  200 non-null    int64
dtypes: int64(2), object(6)
memory usage: 12.6+ KB

========================================

=== 2. عدد الـ Nulls في كل عمود ===
customer_id                 0
customer_name               0
customer_type               0
credit_terms_days           0
primary_freight_type        0
account_status              0
contract_start_date         0
annual_revenue_potential    0
dtype: int64

========================================

=== 3. عدد الصفوف المكررة بالكامل ===
Total Duplicates: 0

========================================

=== 4. الإحصاءات الوصفية ===

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
count,200,200,200,200.000000,200,200,200,2.000000e+02
unique,200,107,3,NaN,6,2,173,NaN
top,CUST00001,First Group,Contract,NaN,Automotive,Active,2020-06-09,NaN
freq,1,7,75,NaN,41,168,4,NaN
mean,NaN,NaN,NaN,37.650000,NaN,NaN,NaN,2.688237e+06
std,NaN,NaN,NaN,17.078815,NaN,NaN,NaN,1.454957e+06
min,NaN,NaN,NaN,15.000000,NaN,NaN,NaN,1.016410e+05
25%,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,1.405872e+06
50%,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,2.784584e+06
75%,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,3.859272e+06
max,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,4.990599e+06

========================================

=== 5. عينة من أول 5 صفوف ===

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [5]:
print("--- Skewness Calculation ---")
print(customers[['credit_terms_days', 'annual_revenue_potential']].skew())

print("\n--- Outliers Detection via IQR ---")
for col in ['credit_terms_days', 'annual_revenue_potential']:
    q1 = customers[col].quantile(0.25)
    q3 = customers[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = customers[(customers[col] < lower_bound) | (customers[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

print("\n--- Categorical Columns Unique Values ---")
print(customers['customer_type'].value_counts())
print("-" * 30)
print(customers['account_status'].value_counts())
print("-" * 30)
print(customers['primary_freight_type'].value_counts())

customers['contract_start_date'] = pd.to_datetime(customers['contract_start_date'])

print("\n--- Final Data Types Verification ---")
print(customers.dtypes)

--- Skewness Calculation ---
credit_terms_days           0.037003
annual_revenue_potential   -0.058837
dtype: float64

--- Outliers Detection via IQR ---
credit_terms_days outliers count: 0
annual_revenue_potential outliers count: 0

--- Categorical Columns Unique Values ---
customer_type
Contract     75
Spot         63
Dedicated    62
Name: count, dtype: int64
------------------------------
account_status
Active      168
Inactive     32
Name: count, dtype: int64
------------------------------
primary_freight_type
Automotive        41
Food/Beverage     37
Retail            35
Electronics       33
Consumer Goods    30
General           24
Name: count, dtype: int64

--- Final Data Types Verification ---
customer_id                         object
customer_name                       object
customer_type                       object
credit_terms_days                    int64
primary_freight_type                object
account_status                      object
contract_start_date         datetime64[ns]
annual_revenue_potential             int64
dtype: object

In [6]:
import os

text_columns = ['customer_id', 'customer_name', 'customer_type', 'primary_freight_type', 'account_status']
for col in text_columns:
    customers[col] = customers[col].astype(str).str.strip()

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)

final_file_path = os.path.join(save_path, "customers.csv")
customers.to_csv(final_file_path, index=False)

print("Text columns stripped successfully")
print("Data types verified")
print("File successfully saved to:", final_file_path)

Text columns stripped successfully
Data types verified
File successfully saved to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\customers.csv

**2-delivery_events EDA and cleaning if it needs**

In [7]:
print("=== 1. Table Info and Data Types ===")
delivery_events.info()

print("\n" + "="*40 + "\n")

print("=== 2. Null Values Count ===")
print(delivery_events.isna().sum())

print("\n" + "="*40 + "\n")

print("=== 3. Total Duplicated Rows ===")
print(f"Total Duplicates: {delivery_events.duplicated().sum()}")

print("\n" + "="*40 + "\n")

print("=== 4. Descriptive Statistics ===")
print(delivery_events.describe(include='all'))

print("\n" + "="*40 + "\n")

print("=== 5. First 5 Rows Sample ===")
print(delivery_events.head())

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  object
 1   load_id             170820 non-null  object
 2   trip_id             170820 non-null  object
 3   event_type          170820 non-null  object
 4   facility_id         170820 non-null  object
 5   scheduled_datetime  170820 non-null  object
 6   actual_datetime     170820 non-null  object
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  object
 10  location_state      170820 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 13.2+ MB

========================================

=== 2. Null Values Count ===
event_id              0
load_id               0
trip_id               0
event_type            0
facility_id           0
scheduled_datetime    0
actual_datetime       0
detention_minutes     0
on_time_flag          0
location_city         0
location_state        0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
           event_id       load_id       trip_id event_type facility_id  \
count        170820        170820        170820     170820      170820
unique       170820         85410         85410          2          50
top     EVT00000001  LOAD00000001  TRIP00000001     Pickup    FAC00028
freq              1             2             2      85410        3580
mean            NaN           NaN           NaN        NaN         NaN
std             NaN           NaN           NaN        NaN         NaN
min             NaN           NaN           NaN        NaN         NaN
25%             NaN           NaN           NaN        NaN         NaN
50%             NaN           NaN           NaN        NaN         NaN
75%             NaN           NaN           NaN        NaN         NaN
max             NaN           NaN           NaN        NaN         NaN

                scheduled_datetime             actual_datetime  \
count                       170820                      170820
unique                       99624                      170820
top     2022-02-03 07:00:00.000000  2022-01-01 20:58:55.918185
freq                            17                           1
mean                           NaN                         NaN
std                            NaN                         NaN
min                            NaN                         NaN
25%                            NaN                         NaN
50%                            NaN                         NaN
75%                            NaN                         NaN
max                            NaN                         NaN

        detention_minutes on_time_flag location_city location_state
count       170820.000000       170820        170820         170820
unique                NaN            2            20             19
top                   NaN         True   Kansas City             TX
freq                  NaN        95095         14562          17542
mean            91.537460          NaN           NaN            NaN
std             68.652514          NaN           NaN            NaN
min              0.000000          NaN           NaN            NaN
25%             29.000000          NaN           NaN            NaN
50%             88.000000          NaN           NaN            NaN
75%            147.000000          NaN           NaN            NaN
max            239.000000          NaN           NaN            NaN

========================================

=== 5. First 5 Rows Sample ===
      event_id       load_id       trip_id event_type facility_id  \
0  EVT00000001  LOAD00000001  TRIP00000001     Pickup    FAC00034
1  EVT00000002  LOAD00000001  TRIP00000001   Delivery    FAC00046
2  EVT00000003  LOAD00000002  TRIP00000002     Pickup    FAC00015
3  EVT00000004  LOAD00000002  TRIP00000002   Delivery    FAC00050
4  EVT00000005  LOAD00000003  TRIP00000003     Pickup    FAC00001

           scheduled_datetime             actual_datetime  detention_minutes  \
0  2022-01-01 18:00:00.000000  2022-01-01 20:58:55.918185                  0
1  2022-01-02 23:10:55.918185  2022-01-02 21:30:22.142060                230
2  2022-01-01 18:00:00.000000  2022-01-01 17:37:26.608430                 62
3  2022-01-02 02:13:26.608430  2022-01-02 05:55:46.238257                 67
4  2022-01-01 08:00:00.000000  2022-01-01 07:28:02.169634                 83

   on_time_flag location_city location_state
0         False       Houston             TX
1          True       Detroit             MI
2          True   Kansas City             MO
3         False  Indianapolis             IN
4          True      Columbus             OH

In [8]:
print("--- Skewness Calculation ---")
print(delivery_events['detention_minutes'].skew())

print("\n--- Outliers Detection via IQR ---")
q1 = delivery_events['detention_minutes'].quantile(0.25)
q3 = delivery_events['detention_minutes'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
outliers = delivery_events[(delivery_events['detention_minutes'] < lower_bound) | (delivery_events['detention_minutes'] > upper_bound)]
print(f"detention_minutes outliers count: {len(outliers)}")

delivery_events['scheduled_datetime'] = pd.to_datetime(delivery_events['scheduled_datetime'])
delivery_events['actual_datetime'] = pd.to_datetime(delivery_events['actual_datetime'])

text_columns = ['event_id', 'load_id', 'trip_id', 'event_type', 'facility_id', 'location_city', 'location_state']
for col in text_columns:
    delivery_events[col] = delivery_events[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(delivery_events.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "delivery_events.csv")
delivery_events.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
0.26460249744989034

--- Outliers Detection via IQR ---
detention_minutes outliers count: 0

--- Final Data Types Verification ---
event_id                      object
load_id                       object
trip_id                       object
event_type                    object
facility_id                   object
scheduled_datetime    datetime64[ns]
actual_datetime       datetime64[ns]
detention_minutes              int64
on_time_flag                    bool
location_city                 object
location_state                object
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\delivery_events.csv

**3-Drivers EDA and cleaning if it needs**

In [9]:
print("=== 1. Table Info and Data Types ===")
drivers.info()

print("\n" + "="*40 + "\n")

print("=== 2. Null Values Count ===")
print(drivers.isna().sum())

print("\n" + "="*40 + "\n")

print("=== 3. Total Duplicated Rows ===")
print(f"Total Duplicates: {drivers.duplicated().sum()}")

print("\n" + "="*40 + "\n")

print("=== 4. Descriptive Statistics ===")
print(drivers.describe(include='all'))

print("\n" + "="*40 + "\n")

print("=== 5. First 5 Rows Sample ===")
print(drivers.head())

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          150 non-null    object
 1   first_name         150 non-null    object
 2   last_name          150 non-null    object
 3   hire_date          150 non-null    object
 4   termination_date   26 non-null     object
 5   license_number     150 non-null    object
 6   license_state      150 non-null    object
 7   date_of_birth      150 non-null    object
 8   home_terminal      150 non-null    object
 9   employment_status  150 non-null    object
 10  cdl_class          150 non-null    object
 11  years_experience   150 non-null    int64
dtypes: int64(1), object(11)
memory usage: 14.2+ KB

========================================

=== 2. Null Values Count ===
driver_id              0
first_name             0
last_name              0
hire_date              0
termination_date     124
license_number         0
license_state          0
date_of_birth          0
home_terminal          0
employment_status      0
cdl_class              0
years_experience       0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
       driver_id first_name last_name   hire_date termination_date  \
count        150        150       150         150               26
unique       150         20        20         147               26
top     DRV00001     Thomas  Anderson  2017-09-28       2021-05-17
freq           1         13        13           2                1
mean         NaN        NaN       NaN         NaN              NaN
std          NaN        NaN       NaN         NaN              NaN
min          NaN        NaN       NaN         NaN              NaN
25%          NaN        NaN       NaN         NaN              NaN
50%          NaN        NaN       NaN         NaN              NaN
75%          NaN        NaN       NaN         NaN              NaN
max          NaN        NaN       NaN         NaN              NaN

       license_number license_state date_of_birth home_terminal  \
count             150           150           150           150
unique            150            23           148            25
top       DL673510887            TX    1989-12-10      New York
freq                1            13             2            10
mean              NaN           NaN           NaN           NaN
std               NaN           NaN           NaN           NaN
min               NaN           NaN           NaN           NaN
25%               NaN           NaN           NaN           NaN
50%               NaN           NaN           NaN           NaN
75%               NaN           NaN           NaN           NaN
max               NaN           NaN           NaN           NaN

       employment_status cdl_class  years_experience
count                150       150        150.000000
unique                 2         1               NaN
top               Active         A               NaN
freq                 124       150               NaN
mean                 NaN       NaN         13.493333
std                  NaN       NaN          6.958889
min                  NaN       NaN          2.000000
25%                  NaN       NaN          7.250000
50%                  NaN       NaN         13.500000
75%                  NaN       NaN         20.000000
max                  NaN       NaN         25.000000

========================================

=== 5. First 5 Rows Sample ===
  driver_id first_name  last_name   hire_date termination_date license_number  \
0  DRV00001   Jennifer  Hernandez  2014-10-31              NaN    DL673510887
1  DRV00002    William     Martin  2020-10-02              NaN    DL128955006
2  DRV00003    Charles  Hernandez  2021-09-21              NaN    DL523076025
3  DRV00004    Barbara      Brown  2013-09-08              NaN    DL735540030
4  DRV00005       Mary   Martinez  2018-12-02              NaN    DL706011277

  license_state date_of_birth   home_terminal employment_status cdl_class  \
0            WA    1973-11-07          Denver            Active         A
1            GA    1976-11-03        Columbus            Active         A
2            NC    1970-04-06  Salt Lake City            Active         A
3            WA    1995-02-06          Denver            Active         A
4            AZ    1960-07-15         Chicago            Active         A

   years_experience
0                 3
1                20
2                19
3                19
4                12

In [13]:
print("--- Skewness Calculation ---")
print(drivers['years_experience'].skew())

drivers['hire_date'] = pd.to_datetime(drivers['hire_date'])
drivers['termination_date'] = pd.to_datetime(drivers['termination_date'])
drivers['date_of_birth'] = pd.to_datetime(drivers['date_of_birth'])

text_columns = ['driver_id', 'first_name', 'last_name', 'license_number', 'license_state', 'home_terminal', 'employment_status', 'cdl_class']
for col in text_columns:
    drivers[col] = drivers[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(drivers.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "drivers.csv")
drivers.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
-0.039904065204803656

--- Final Data Types Verification ---
driver_id                    object
first_name                   object
last_name                    object
hire_date            datetime64[ns]
termination_date     datetime64[ns]
license_number               object
license_state                object
date_of_birth        datetime64[ns]
home_terminal                object
employment_status            object
cdl_class                    object
years_experience              int64
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\drivers.csv

**4-driver_monthly_metrics EDA and cleaning if it needs**

In [15]:
# a function to help in EDA 
def tableEDA(df):
    print("=== 1. Table Info and Data Types ===")
    df.info()
    print("\n" + "="*40 + "\n")
    print("=== 2. Null Values Count ===")
    print(df.isna().sum())
    print("\n" + "="*40 + "\n")
    print("=== 3. Total Duplicated Rows ===")
    print(f"Total Duplicates: {df.duplicated().sum()}")
    print("\n" + "="*40 + "\n")
    print("=== 4. Descriptive Statistics ===")
    print(df.describe(include='all'))
    print("\n" + "="*40 + "\n")
    print("=== 5. First 5 Rows Sample ===")
    print(df.head())

In [16]:
tableEDA(driver_monthly_metrics)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4464 non-null   object
 1   month                  4464 non-null   object
 2   trips_completed        4464 non-null   int64
 3   total_miles            4464 non-null   int64
 4   total_revenue          4464 non-null   float64
 5   average_mpg            4464 non-null   float64
 6   total_fuel_gallons     4464 non-null   float64
 7   on_time_delivery_rate  4464 non-null   float64
 8   average_idle_hours     4464 non-null   float64
dtypes: float64(5), int64(2), object(2)
memory usage: 314.0+ KB

========================================

=== 2. Null Values Count ===
driver_id                0
month                    0
trips_completed          0
total_miles              0
total_revenue            0
average_mpg              0
total_fuel_gallons       0
on_time_delivery_rate    0
average_idle_hours       0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
       driver_id       month  trips_completed   total_miles  total_revenue  \
count       4464        4464      4464.000000   4464.000000    4464.000000
unique       124          36              NaN           NaN            NaN
top     DRV00001  2022-01-01              NaN           NaN            NaN
freq          36         124              NaN           NaN            NaN
mean         NaN         NaN        18.749104  26812.792339   57630.947713
std          NaN         NaN         4.387080   7253.534265   15899.349196
min          NaN         NaN         5.000000   3310.000000    7096.560000
25%          NaN         NaN        16.000000  21783.000000   46314.052500
50%          NaN         NaN        19.000000  26409.500000   56652.715000
75%          NaN         NaN        22.000000  31474.750000   67964.807500
max          NaN         NaN        37.000000  57954.000000  124579.530000

        average_mpg  total_fuel_gallons  on_time_delivery_rate  \
count   4464.000000         4464.000000            4464.000000
unique          NaN                 NaN                    NaN
top             NaN                 NaN                    NaN
freq            NaN                 NaN                    NaN
mean       6.501862         4158.631698               0.445996
std        0.140353         1132.037704               0.119988
min        6.010000          521.900000               0.000000
25%        6.410000         3372.500000               0.364000
50%        6.500000         4083.950000               0.444000
75%        6.600000         4882.400000               0.526000
max        7.070000         9007.500000               0.833000

        average_idle_hours
count          4464.000000
unique                 NaN
top                    NaN
freq                   NaN
mean              7.011738
std               0.683257
min               4.400000
25%               6.600000
50%               7.000000
75%               7.500000
max               9.700000

========================================

=== 5. First 5 Rows Sample ===
  driver_id       month  trips_completed  total_miles  total_revenue  \
0  DRV00001  2022-01-01               26        36620       79141.59
1  DRV00001  2022-02-01                9        13515       27133.87
2  DRV00001  2022-03-01               20        30361       62399.62
3  DRV00001  2022-04-01               19        28127       68161.13
4  DRV00001  2022-05-01               14        16071       36256.82

   average_mpg  total_fuel_gallons  on_time_delivery_rate  average_idle_hours
0         6.61              5574.7                  0.385                 8.2
1         6.69              2095.1                  0.333                 6.8
2         6.36              4792.2                  0.550                 7.5
3         6.61              4251.4                  0.474                 8.4
4         6.35              2573.1                  0.214                 6.8

In [17]:
num_cols = ['trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'total_fuel_gallons', 'on_time_delivery_rate', 'average_idle_hours']

print("--- Skewness Calculation ---")
print(driver_monthly_metrics[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = driver_monthly_metrics[col].quantile(0.25)
    q3 = driver_monthly_metrics[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = driver_monthly_metrics[(driver_monthly_metrics[col] < lower_bound) | (driver_monthly_metrics[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

driver_monthly_metrics['month'] = pd.to_datetime(driver_monthly_metrics['month'])

driver_monthly_metrics['driver_id'] = driver_monthly_metrics['driver_id'].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(driver_monthly_metrics.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "driver_monthly_metrics.csv")
driver_monthly_metrics.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
trips_completed          0.169943
total_miles              0.279533
total_revenue            0.307092
average_mpg              0.028802
total_fuel_gallons       0.298469
on_time_delivery_rate    0.019782
average_idle_hours      -0.010269
dtype: float64

--- Outliers Detection via IQR ---
trips_completed outliers count: 19
total_miles outliers count: 34
total_revenue outliers count: 33
average_mpg outliers count: 42
total_fuel_gallons outliers count: 32
on_time_delivery_rate outliers count: 32
average_idle_hours outliers count: 52

--- Final Data Types Verification ---
driver_id                        object
month                    datetime64[ns]
trips_completed                   int64
total_miles                       int64
total_revenue                   float64
average_mpg                     float64
total_fuel_gallons              float64
on_time_delivery_rate           float64
average_idle_hours              float64
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\driver_monthly_metrics.csv

**5-facilities EDA and cleaning if it needs**

In [18]:
tableEDA(facilities)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   facility_id      50 non-null     object
 1   facility_name    50 non-null     object
 2   facility_type    50 non-null     object
 3   city             50 non-null     object
 4   state            50 non-null     object
 5   latitude         50 non-null     float64
 6   longitude        50 non-null     float64
 7   dock_doors       50 non-null     int64
 8   operating_hours  50 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 3.6+ KB

========================================

=== 2. Null Values Count ===
facility_id        0
facility_name      0
facility_type      0
city               0
state              0
latitude           0
longitude          0
dock_doors         0
operating_hours    0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
       facility_id                  facility_name facility_type       city  \
count           50                             50            50         50
unique          50                             35             4         21
top       FAC00001  Nashville Distribution Center    Cross-Dock  Nashville
freq             1                              4            20          5
mean           NaN                            NaN           NaN        NaN
std            NaN                            NaN           NaN        NaN
min            NaN                            NaN           NaN        NaN
25%            NaN                            NaN           NaN        NaN
50%            NaN                            NaN           NaN        NaN
75%            NaN                            NaN           NaN        NaN
max            NaN                            NaN           NaN        NaN

       state   latitude   longitude  dock_doors operating_hours
count     50  50.000000   50.000000   50.000000              50
unique    20        NaN         NaN         NaN               4
top       TX        NaN         NaN         NaN            24/7
freq       5        NaN         NaN         NaN              16
mean     NaN  36.869320  -93.260216   78.580000             NaN
std      NaN   4.880076   13.747687   39.735395             NaN
min      NaN  25.761700 -122.678400   16.000000             NaN
25%      NaN  33.749000  -97.336550   44.750000             NaN
50%      NaN  36.166300  -86.781600   67.500000             NaN
75%      NaN  40.748800  -83.381350  113.750000             NaN
max      NaN  45.515200  -74.006000  150.000000             NaN

========================================

=== 5. First 5 Rows Sample ===
  facility_id                  facility_name        facility_type  \
0    FAC00001    Houston Distribution Center           Cross-Dock
1    FAC00002                Kansas City Hub           Cross-Dock
2    FAC00003  Charlotte Distribution Center  Distribution Center
3    FAC00004    Chicago Distribution Center  Distribution Center
4    FAC00005               Indianapolis Hub  Distribution Center

           city state  latitude  longitude  dock_doors operating_hours
0       Houston    TX   29.7604   -95.3698         125            24/7
1   Kansas City    MO   39.0997   -94.5786          33         7AM-7PM
2     Charlotte    NC   35.2271   -80.8431         138            24/7
3       Chicago    IL   41.8781   -87.6298          38         8AM-5PM
4  Indianapolis    IN   39.7684   -86.1581          56         8AM-5PM

In [19]:
print("--- Skewness Calculation ---")
print(facilities['dock_doors'].skew())

print("\n--- Outliers Detection via IQR ---")
q1 = facilities['dock_doors'].quantile(0.25)
q3 = facilities['dock_doors'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
outliers = facilities[(facilities['dock_doors'] < lower_bound) | (facilities['dock_doors'] > upper_bound)]
print(f"dock_doors outliers count: {len(outliers)}")

text_columns = ['facility_id', 'facility_name', 'facility_type', 'city', 'state', 'operating_hours']
for col in text_columns:
    facilities[col] = facilities[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(facilities.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "facilities.csv")
facilities.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
0.2520106724340488

--- Outliers Detection via IQR ---
dock_doors outliers count: 0

--- Final Data Types Verification ---
facility_id         object
facility_name       object
facility_type       object
city                object
state               object
latitude           float64
longitude          float64
dock_doors           int64
operating_hours     object
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\facilities.csv

**6-fuel_purchases EDA and cleaning if it needs**

In [20]:
tableEDA(fuel_purchases)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196442 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  196442 non-null  object
 1   trip_id           196442 non-null  object
 2   truck_id          192562 non-null  object
 3   driver_id         192454 non-null  object
 4   purchase_date     196442 non-null  object
 5   location_city     196442 non-null  object
 6   location_state    196442 non-null  object
 7   gallons           196442 non-null  float64
 8   price_per_gallon  196442 non-null  float64
 9   total_cost        196442 non-null  float64
 10  fuel_card_number  196442 non-null  object
dtypes: float64(3), object(8)
memory usage: 16.5+ MB

========================================

=== 2. Null Values Count ===
fuel_purchase_id       0
trip_id                0
truck_id            3880
driver_id           3988
purchase_date          0
location_city          0
location_state         0
gallons                0
price_per_gallon       0
total_cost             0
fuel_card_number       0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
       fuel_purchase_id       trip_id  truck_id driver_id  \
count            196442        196442    192562    192454
unique           196442         76939        92       124
top        FUEL00000001  TRIP00063973  TRK00044  DRV00108
freq                  1            11      2283      1722
mean                NaN           NaN       NaN       NaN
std                 NaN           NaN       NaN       NaN
min                 NaN           NaN       NaN       NaN
25%                 NaN           NaN       NaN       NaN
50%                 NaN           NaN       NaN       NaN
75%                 NaN           NaN       NaN       NaN
max                 NaN           NaN       NaN       NaN

              purchase_date location_city location_state        gallons  \
count                196442        196442         196442  196442.000000
unique                26331            25             23            NaN
top     2024-05-22 01:00:00      Columbus             TN            NaN
freq                     21          7981          15690            NaN
mean                    NaN           NaN            NaN     124.815660
std                     NaN           NaN            NaN      43.346522
min                     NaN           NaN            NaN      50.000000
25%                     NaN           NaN            NaN      87.200000
50%                     NaN           NaN            NaN     124.700000
75%                     NaN           NaN            NaN     162.400000
max                     NaN           NaN            NaN     200.000000

        price_per_gallon     total_cost fuel_card_number
count      196442.000000  196442.000000           196442
unique               NaN            NaN           176645
top                  NaN            NaN         FC631170
freq                 NaN            NaN                5
mean            3.898418     486.621965              NaN
std             0.436489     178.616665              NaN
min             3.150000     158.500000              NaN
25%             3.552000     336.240000              NaN
50%             3.856000     480.660000              NaN
75%             4.168000     625.530000              NaN
max             5.000000     997.900000              NaN

========================================

=== 5. First 5 Rows Sample ===
  fuel_purchase_id       trip_id  truck_id driver_id        purchase_date  \
0     FUEL00000001  TRIP00051284  TRK00045  DRV00102  2023-10-22 05:00:00
1     FUEL00000002  TRIP00073723  TRK00013       NaN  2024-08-04 08:00:00
2     FUEL00000003  TRIP00018286  TRK00024  DRV00142  2022-08-23 13:00:00
3     FUEL00000004  TRIP00008465  TRK00018  DRV00047  2022-04-20 00:00:00
4     FUEL00000005  TRIP00069700  TRK00054       NaN  2024-06-13 09:00:00

  location_city location_state  gallons  price_per_gallon  total_cost  \
0      Columbus             MN    131.6             3.399      447.31
1      New York             AZ    139.9             3.180      444.88
2       Seattle             NE    189.3             3.804      720.10
3       Memphis             NY    130.7             3.579      467.78
4      Columbus             AZ    185.3             3.422      634.10

  fuel_card_number
0         FC567161
1         FC717910
2         FC912816
3         FC776357
4         FC391024

In [21]:
num_cols = ['gallons', 'price_per_gallon', 'total_cost']
print("--- Skewness Calculation ---")
print(fuel_purchases[num_cols].skew())


fuel_purchases['truck_id'] = fuel_purchases['truck_id'].fillna('Unknown')
fuel_purchases['driver_id'] = fuel_purchases['driver_id'].fillna('Unknown')


fuel_purchases['purchase_date'] = pd.to_datetime(fuel_purchases['purchase_date'])


text_columns = ['fuel_purchase_id', 'trip_id', 'truck_id', 'driver_id', 'location_city', 'location_state', 'fuel_card_number']
for col in text_columns:
    fuel_purchases[col] = fuel_purchases[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(fuel_purchases.dtypes)

print("\n--- Missing Values Count Verification ---")
print(fuel_purchases.isna().sum())

# Save the cleaned data
save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "fuel_purchases.csv")
fuel_purchases.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
gallons             0.005411
price_per_gallon    0.499638
total_cost          0.205664
dtype: float64

--- Final Data Types Verification ---
fuel_purchase_id            object
trip_id                     object
truck_id                    object
driver_id                   object
purchase_date       datetime64[ns]
location_city               object
location_state              object
gallons                    float64
price_per_gallon           float64
total_cost                 float64
fuel_card_number            object
dtype: object

--- Missing Values Count Verification ---
fuel_purchase_id    0
trip_id             0
truck_id            0
driver_id           0
purchase_date       0
location_city       0
location_state      0
gallons             0
price_per_gallon    0
total_cost          0
fuel_card_number    0
dtype: int64

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\fuel_purchases.csv

**7-loads EDA and cleaning if it needs**

In [22]:
tableEDA(loads)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  object
 1   customer_id          85410 non-null  object
 2   route_id             85410 non-null  object
 3   load_date            85410 non-null  object
 4   load_type            85410 non-null  object
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  object
 11  booking_type         85410 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 7.8+ MB

========================================

=== 2. Null Values Count ===
load_id                0
customer_id            0
route_id               0
load_date              0
load_type              0
weight_lbs             0
pieces                 0
revenue                0
fuel_surcharge         0
accessorial_charges    0
load_status            0
booking_type           0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
             load_id customer_id  route_id   load_date     load_type  \
count          85410       85410     85410       85410         85410
unique         85410         200        58        1096             2
top     LOAD00000001   CUST00181  RTE00047  2022-05-18  Refrigerated
freq               1         497      1628         108         42946
mean             NaN         NaN       NaN         NaN           NaN
std              NaN         NaN       NaN         NaN           NaN
min              NaN         NaN       NaN         NaN           NaN
25%              NaN         NaN       NaN         NaN           NaN
50%              NaN         NaN       NaN         NaN           NaN
75%              NaN         NaN       NaN         NaN           NaN
max              NaN         NaN       NaN         NaN           NaN

          weight_lbs        pieces       revenue  fuel_surcharge  \
count   85410.000000  85410.000000  85410.000000    85410.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean    27477.495305     14.470530   3073.712683      350.972119
std     10095.421857      8.070077   1883.127436      218.034684
min     10000.000000      1.000000    125.930000       13.800000
25%     18724.000000      7.000000   1443.215000      161.530000
50%     27482.000000     14.000000   2827.985000      314.640000
75%     36190.000000     21.000000   4323.157500      499.180000
max     45000.000000     28.000000   8125.220000      891.820000

        accessorial_charges load_status booking_type
count          85410.000000       85410        85410
unique                  NaN           1            3
top                     NaN   Completed    Dedicated
freq                    NaN       85410        42337
mean              71.643836         NaN          NaN
std               70.018823         NaN          NaN
min                0.000000         NaN          NaN
25%                0.000000         NaN          NaN
50%               50.000000         NaN          NaN
75%              100.000000         NaN          NaN
max              200.000000         NaN          NaN

========================================

=== 5. First 5 Rows Sample ===
        load_id customer_id  route_id   load_date     load_type  weight_lbs  \
0  LOAD00000001   CUST00183  RTE00019  2022-01-01       Dry Van       19178
1  LOAD00000002   CUST00076  RTE00058  2022-01-01       Dry Van       27761
2  LOAD00000003   CUST00027  RTE00048  2022-01-01  Refrigerated       35594
3  LOAD00000004   CUST00088  RTE00013  2022-01-01  Refrigerated       33274
4  LOAD00000005   CUST00185  RTE00020  2022-01-01       Dry Van       40257

   pieces  revenue  fuel_surcharge  accessorial_charges load_status  \
0      13  3045.23          406.72                  100   Completed
1      22  1224.48           98.61                    0   Completed
2      16  7171.12          792.88                    0   Completed
3      10  1308.20          141.33                   50   Completed
4      10  3317.18          738.48                    0   Completed

  booking_type
0         Spot
1    Dedicated
2         Spot
3         Spot
4         Spot

In [23]:
num_cols = ['weight_lbs', 'pieces', 'revenue', 'fuel_surcharge', 'accessorial_charges']

print("--- Skewness Calculation ---")
print(loads[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = loads[col].quantile(0.25)
    q3 = loads[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = loads[(loads[col] < lower_bound) | (loads[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

loads['load_date'] = pd.to_datetime(loads['load_date'])

text_columns = ['load_id', 'customer_id', 'route_id', 'load_type', 'load_status', 'booking_type']
for col in text_columns:
    loads[col] = loads[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(loads.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "loads.csv")
loads.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
weight_lbs            -0.000388
pieces                 0.006095
revenue                0.530232
fuel_surcharge         0.554538
accessorial_charges    0.539440
dtype: float64

--- Outliers Detection via IQR ---
weight_lbs outliers count: 0
pieces outliers count: 0
revenue outliers count: 0
fuel_surcharge outliers count: 0
accessorial_charges outliers count: 0

--- Final Data Types Verification ---
load_id                        object
customer_id                    object
route_id                       object
load_date              datetime64[ns]
load_type                      object
weight_lbs                      int64
pieces                          int64
revenue                       float64
fuel_surcharge                float64
accessorial_charges             int64
load_status                    object
booking_type                   object
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\loads.csv

**8-loads EDA and cleaning if it needs**

In [24]:
tableEDA(maintenance_records)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   object
 1   truck_id             2920 non-null   object
 2   maintenance_date     2920 non-null   object
 3   maintenance_type     2920 non-null   object
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   object
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 273.9+ KB

========================================

=== 2. Null Values Count ===
maintenance_id         0
truck_id               0
maintenance_date       0
maintenance_type       0
odometer_reading       0
labor_hours            0
labor_cost             0
parts_cost             0
total_cost             0
facility_location      0
downtime_hours         0
service_description    0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
       maintenance_id  truck_id maintenance_date maintenance_type  \
count            2920      2920             2920             2920
unique           2920       120             1020                7
top     MAINT00000001  TRK00003       2023-10-25       Inspection
freq                1        41                9              432
mean              NaN       NaN              NaN              NaN
std               NaN       NaN              NaN              NaN
min               NaN       NaN              NaN              NaN
25%               NaN       NaN              NaN              NaN
50%               NaN       NaN              NaN              NaN
75%               NaN       NaN              NaN              NaN
max               NaN       NaN              NaN              NaN

        odometer_reading  labor_hours   labor_cost   parts_cost   total_cost  \
count        2920.000000  2920.000000  2920.000000  2920.000000  2920.000000
unique               NaN          NaN          NaN          NaN          NaN
top                  NaN          NaN          NaN          NaN          NaN
freq                 NaN          NaN          NaN          NaN          NaN
mean       401534.787671     4.178459   438.529825  1523.995271  1962.525096
std        207093.951665     2.131282   229.989621  1103.739471  1135.418952
min         50156.000000     0.500000    43.280000     0.140000    60.820000
25%        215376.500000     2.300000   242.600000   443.125000   906.752500
50%        407955.000000     4.200000   435.200000  1465.415000  1896.045000
75%        585079.000000     6.000000   622.382500  2489.445000  2938.257500
max        749875.000000     8.000000   976.870000  3498.610000  4426.570000

       facility_location  downtime_hours service_description
count               2920     2920.000000                2920
unique                25             NaN                  21
top          Los Angeles             NaN    Scheduled Engine
freq                 139             NaN                 152
mean                 NaN       24.736473                 NaN
std                  NaN       13.312263                 NaN
min                  NaN        2.000000                 NaN
25%                  NaN       13.300000                 NaN
50%                  NaN       24.750000                 NaN
75%                  NaN       36.225000                 NaN
max                  NaN       48.000000                 NaN

========================================

=== 5. First 5 Rows Sample ===
  maintenance_id  truck_id maintenance_date maintenance_type  \
0  MAINT00000001  TRK00085       2022-01-01       Inspection
1  MAINT00000002  TRK00041       2022-01-01             Tire
2  MAINT00000003  TRK00090       2022-01-01       Preventive
3  MAINT00000004  TRK00056       2022-01-02       Inspection
4  MAINT00000005  TRK00029       2022-01-02           Repair

   odometer_reading  labor_hours  labor_cost  parts_cost  total_cost  \
0            400255          7.8      781.42       10.41      791.83
1            268041          0.9       80.91     3207.16     3288.07
2            698915          7.2      733.18     1570.57     2303.75
3            416522          2.8      298.80       67.48      366.28
4            179968          4.6      409.08      982.59     1391.67

  facility_location  downtime_hours   service_description
0       Kansas City            22.2  Emergency Inspection
1           Seattle             8.0        Scheduled Tire
2             Miami            16.5    Routine Preventive
3       Kansas City            34.6  Emergency Inspection
4             Omaha             4.4      Emergency Repair

In [25]:
num_cols = ['odometer_reading', 'labor_hours', 'labor_cost', 'parts_cost', 'total_cost', 'downtime_hours']

print("--- Skewness Calculation ---")
print(maintenance_records[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = maintenance_records[col].quantile(0.25)
    q3 = maintenance_records[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = maintenance_records[(maintenance_records[col] < lower_bound) | (maintenance_records[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

maintenance_records['maintenance_date'] = pd.to_datetime(maintenance_records['maintenance_date'])

text_columns = ['maintenance_id', 'truck_id', 'maintenance_type', 'facility_location', 'service_description']
for col in text_columns:
    maintenance_records[col] = maintenance_records[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(maintenance_records.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "maintenance_records.csv")
maintenance_records.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
odometer_reading   -0.029097
labor_hours         0.008014
labor_cost          0.126956
parts_cost          0.151441
total_cost          0.159831
downtime_hours      0.008861
dtype: float64

--- Outliers Detection via IQR ---
odometer_reading outliers count: 0
labor_hours outliers count: 0
labor_cost outliers count: 0
parts_cost outliers count: 0
total_cost outliers count: 0
downtime_hours outliers count: 0

--- Final Data Types Verification ---
maintenance_id                 object
truck_id                       object
maintenance_date       datetime64[ns]
maintenance_type               object
odometer_reading                int64
labor_hours                   float64
labor_cost                    float64
parts_cost                    float64
total_cost                    float64
facility_location              object
downtime_hours                float64
service_description            object
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\maintenance_records.csv

**9-routes EDA and cleaning if it needs**

In [26]:
tableEDA(routes)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     object
 1   origin_city             58 non-null     object
 2   origin_state            58 non-null     object
 3   destination_city        58 non-null     object
 4   destination_state       58 non-null     object
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), object(5)
memory usage: 4.2+ KB

========================================

=== 2. Null Values Count ===
route_id                  0
origin_city               0
origin_state              0
destination_city          0
destination_state         0
typical_distance_miles    0
base_rate_per_mile        0
fuel_surcharge_rate       0
typical_transit_days      0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
        route_id  origin_city origin_state destination_city destination_state  \
count         58           58           58               58                58
unique        58           18           17               19                18
top     RTE00001  Kansas City           TX      Los Angeles                CA
freq           1            6            7                6                 6
mean         NaN          NaN          NaN              NaN               NaN
std          NaN          NaN          NaN              NaN               NaN
min          NaN          NaN          NaN              NaN               NaN
25%          NaN          NaN          NaN              NaN               NaN
50%          NaN          NaN          NaN              NaN               NaN
75%          NaN          NaN          NaN              NaN               NaN
max          NaN          NaN          NaN              NaN               NaN

        typical_distance_miles  base_rate_per_mile  fuel_surcharge_rate  \
count                58.000000           58.000000            58.000000
unique                     NaN                 NaN                  NaN
top                        NaN                 NaN                  NaN
freq                       NaN                 NaN                  NaN
mean               1391.500000            2.196724             0.248793
std                 782.833209            0.368788             0.061817
min                  92.000000            1.520000             0.150000
25%                 700.750000            1.902500             0.190000
50%                1271.000000            2.230000             0.245000
75%                2085.250000            2.480000             0.300000
max                3141.000000            2.790000             0.340000

        typical_transit_days
count              58.000000
unique                   NaN
top                      NaN
freq                     NaN
mean                2.120690
std                 1.155879
min                 1.000000
25%                 1.000000
50%                 2.000000
75%                 3.000000
max                 5.000000

========================================

=== 5. First 5 Rows Sample ===
   route_id origin_city origin_state destination_city destination_state  \
0  RTE00001     Atlanta           GA          Chicago                IL
1  RTE00002     Atlanta           GA            Miami                FL
2  RTE00003     Chicago           IL      Los Angeles                CA
3  RTE00004     Chicago           IL         Portland                OR
4  RTE00005     Chicago           IL        Las Vegas                NV

   typical_distance_miles  base_rate_per_mile  fuel_surcharge_rate  \
0                     677                1.70                 0.19
1                     697                2.08                 0.22
2                    2003                2.55                 0.29
3                    2017                1.84                 0.19
4                    1749                2.41                 0.26

   typical_transit_days
0                     1
1                     1
2                     3
3                     3
4                     3

In [27]:
num_cols = ['typical_distance_miles', 'base_rate_per_mile', 'fuel_surcharge_rate', 'typical_transit_days']

print("--- Skewness Calculation ---")
print(routes[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = routes[col].quantile(0.25)
    q3 = routes[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = routes[(routes[col] < lower_bound) | (routes[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

text_columns = ['route_id', 'origin_city', 'origin_state', 'destination_city', 'destination_state']
for col in text_columns:
    routes[col] = routes[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(routes.dtypes)

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "routes.csv")
routes.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
typical_distance_miles    0.263744
base_rate_per_mile       -0.173964
fuel_surcharge_rate       0.054133
typical_transit_days      0.603885
dtype: float64

--- Outliers Detection via IQR ---
typical_distance_miles outliers count: 0
base_rate_per_mile outliers count: 0
fuel_surcharge_rate outliers count: 0
typical_transit_days outliers count: 0

--- Final Data Types Verification ---
route_id                   object
origin_city                object
origin_state               object
destination_city           object
destination_state          object
typical_distance_miles      int64
base_rate_per_mile        float64
fuel_surcharge_rate       float64
typical_transit_days        int64
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\routes.csv

**10-safety_incidents EDA and cleaning if it needs**

In [28]:
tableEDA(safety_incidents)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   incident_id          170 non-null    object
 1   trip_id              170 non-null    object
 2   truck_id             169 non-null    object
 3   driver_id            169 non-null    object
 4   incident_date        170 non-null    object
 5   incident_type        170 non-null    object
 6   location_city        170 non-null    object
 7   location_state       170 non-null    object
 8   at_fault_flag        170 non-null    bool
 9   injury_flag          170 non-null    bool
 10  vehicle_damage_cost  170 non-null    float64
 11  cargo_damage_cost    170 non-null    float64
 12  claim_amount         170 non-null    float64
 13  preventable_flag     170 non-null    bool
 14  description          170 non-null    object
dtypes: bool(3), float64(3), object(9)
memory usage: 16.6+ KB

========================================

=== 2. Null Values Count ===
incident_id            0
trip_id                0
truck_id               1
driver_id              1
incident_date          0
incident_type          0
location_city          0
location_state         0
at_fault_flag          0
injury_flag            0
vehicle_damage_cost    0
cargo_damage_cost      0
claim_amount           0
preventable_flag       0
description            0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
        incident_id       trip_id  truck_id driver_id        incident_date  \
count           170           170       169       169                  170
unique          170           170        80        92                  169
top     INC00000001  TRIP00036079  TRK00007  DRV00058  2023-07-08 02:00:00
freq              1             1         6         7                    2
mean            NaN           NaN       NaN       NaN                  NaN
std             NaN           NaN       NaN       NaN                  NaN
min             NaN           NaN       NaN       NaN                  NaN
25%             NaN           NaN       NaN       NaN                  NaN
50%             NaN           NaN       NaN       NaN                  NaN
75%             NaN           NaN       NaN       NaN                  NaN
max             NaN           NaN       NaN       NaN                  NaN

        incident_type location_city location_state at_fault_flag injury_flag  \
count             170           170            170           170         170
unique              5            25             23             2           2
top     DOT Violation       Chicago             TN         False       False
freq               39            11             18           116         137
mean              NaN           NaN            NaN           NaN         NaN
std               NaN           NaN            NaN           NaN         NaN
min               NaN           NaN            NaN           NaN         NaN
25%               NaN           NaN            NaN           NaN         NaN
50%               NaN           NaN            NaN           NaN         NaN
75%               NaN           NaN            NaN           NaN         NaN
max               NaN           NaN            NaN           NaN         NaN

        vehicle_damage_cost  cargo_damage_cost  claim_amount preventable_flag  \
count            170.000000         170.000000    170.000000              170
unique                  NaN                NaN           NaN                2
top                     NaN                NaN           NaN            False
freq                    NaN                NaN           NaN              106
mean            9432.712412        6174.180647  15606.893059              NaN
std             8549.031425       12989.250393  15082.128331              NaN
min                0.000000           0.000000      0.000000              NaN
25%                0.000000           0.000000   2108.275000              NaN
50%             8035.265000           0.000000  13627.185000              NaN
75%            17688.742500        1790.562500  21988.787500              NaN
max            24614.160000       49744.070000  64245.720000              NaN

                              description
count                                 170
unique                                 12
top     Severe incident involving weather
freq                                   18
mean                                  NaN
std                                   NaN
min                                   NaN
25%                                   NaN
50%                                   NaN
75%                                   NaN
max                                   NaN

========================================

=== 5. First 5 Rows Sample ===
   incident_id       trip_id  truck_id driver_id        incident_date  \
0  INC00000001  TRIP00036079  TRK00006  DRV00006  2023-04-09 14:00:00
1  INC00000002  TRIP00032462  TRK00084  DRV00006  2023-02-19 11:00:00
2  INC00000003  TRIP00067583  TRK00106  DRV00119  2024-05-20 01:00:00
3  INC00000004  TRIP00049128  TRK00085  DRV00134  2023-09-26 03:00:00
4  INC00000005  TRIP00062884  TRK00014  DRV00133  2024-03-20 14:00:00

        incident_type location_city location_state  at_fault_flag  \
0    Moving Violation      Columbus             PA           True
1    Moving Violation      Columbus             NC          False
2  Customer Complaint       Seattle             OK           True
3    Equipment Damage   Kansas City             TN           True
4       DOT Violation     Las Vegas             IN          False

   injury_flag  vehicle_damage_cost  cargo_damage_cost  claim_amount  \
0        False             12629.26               0.00      12629.26
1        False              2700.70           14284.24      16984.94
2        False             24302.32               0.00      24302.32
3        False              4879.13               0.00       4879.13
4        False             14951.40               0.00      14951.40

   preventable_flag                            description
0              True    Severe incident involving equipment
1             False      Severe incident involving weather
2              True       Minor incident involving traffic
3              True  Moderate incident involving equipment
4             False  Minor incident involving other driver

In [29]:
num_cols = ['vehicle_damage_cost', 'cargo_damage_cost', 'claim_amount']

print("--- Skewness Calculation ---")
print(safety_incidents[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = safety_incidents[col].quantile(0.25)
    q3 = safety_incidents[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = safety_incidents[(safety_incidents[col] < lower_bound) | (safety_incidents[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

safety_incidents['truck_id'] = safety_incidents['truck_id'].fillna('Unknown')
safety_incidents['driver_id'] = safety_incidents['driver_id'].fillna('Unknown')

safety_incidents['incident_date'] = pd.to_datetime(safety_incidents['incident_date'])

text_columns = ['incident_id', 'trip_id', 'truck_id', 'driver_id', 'incident_type', 'location_city', 'location_state', 'description']
for col in text_columns:
    safety_incidents[col] = safety_incidents[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(safety_incidents.dtypes)

print("\n--- Missing Values Count Verification ---")
print(safety_incidents.isna().sum())

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "safety_incidents.csv")
safety_incidents.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
vehicle_damage_cost    0.274051
cargo_damage_cost      2.069741
claim_amount           1.095424
dtype: float64

--- Outliers Detection via IQR ---
vehicle_damage_cost outliers count: 0
cargo_damage_cost outliers count: 39
claim_amount outliers count: 3

--- Final Data Types Verification ---
incident_id                    object
trip_id                        object
truck_id                       object
driver_id                      object
incident_date          datetime64[ns]
incident_type                  object
location_city                  object
location_state                 object
at_fault_flag                    bool
injury_flag                      bool
vehicle_damage_cost           float64
cargo_damage_cost             float64
claim_amount                  float64
preventable_flag                 bool
description                    object
dtype: object

--- Missing Values Count Verification ---
incident_id            0
trip_id                0
truck_id               0
driver_id              0
incident_date          0
incident_type          0
location_city          0
location_state         0
at_fault_flag          0
injury_flag            0
vehicle_damage_cost    0
cargo_damage_cost      0
claim_amount           0
preventable_flag       0
description            0
dtype: int64

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\safety_incidents.csv

**11-trailers EDA and cleaning if it needs**

In [30]:
tableEDA(trailers)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trailer_id        180 non-null    object
 1   trailer_number    180 non-null    int64
 2   trailer_type      180 non-null    object
 3   length_feet       180 non-null    int64
 4   model_year        180 non-null    int64
 5   vin               180 non-null    object
 6   acquisition_date  180 non-null    object
 7   status            180 non-null    object
 8   current_location  180 non-null    object
dtypes: int64(3), object(6)
memory usage: 12.8+ KB

========================================

=== 2. Null Values Count ===
trailer_id          0
trailer_number      0
trailer_type        0
length_feet         0
model_year          0
vin                 0
acquisition_date    0
status              0
current_location    0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
       trailer_id  trailer_number trailer_type  length_feet   model_year  \
count         180      180.000000          180        180.0   180.000000
unique        180             NaN            2          NaN          NaN
top      TRL00001             NaN      Dry Van          NaN          NaN
freq            1             NaN           94          NaN          NaN
mean          NaN     5881.677778          NaN         53.0  2019.144444
std           NaN     2491.074206          NaN          0.0     2.940988
min           NaN     1072.000000          NaN         53.0  2015.000000
25%           NaN     3802.750000          NaN         53.0  2016.000000
50%           NaN     6150.500000          NaN         53.0  2019.000000
75%           NaN     7998.000000          NaN         53.0  2022.000000
max           NaN     9939.000000          NaN         53.0  2024.000000

                       vin acquisition_date  status current_location
count                  180              180     180              180
unique                 180              173       1               25
top     1AV889081755621178       2016-03-02  Active      Los Angeles
freq                     1                2     180               14
mean                   NaN              NaN     NaN              NaN
std                    NaN              NaN     NaN              NaN
min                    NaN              NaN     NaN              NaN
25%                    NaN              NaN     NaN              NaN
50%                    NaN              NaN     NaN              NaN
75%                    NaN              NaN     NaN              NaN
max                    NaN              NaN     NaN              NaN

========================================

=== 5. First 5 Rows Sample ===
  trailer_id  trailer_number  trailer_type  length_feet  model_year  \
0   TRL00001            4290  Refrigerated           53        2016
1   TRL00002            8848       Dry Van           53        2018
2   TRL00003            6147       Dry Van           53        2022
3   TRL00004            3910       Dry Van           53        2024
4   TRL00005            7524       Dry Van           53        2016

                  vin acquisition_date  status current_location
0  1AV889081755621178       2018-05-11  Active      Kansas City
1  1BU942062588832828       2018-11-24  Active      Kansas City
2  1AV669057807416326       2019-01-28  Active        Milwaukee
3  1AV544000060905105       2018-08-27  Active         New York
4  1AV170126369813275       2019-11-22  Active        Las Vegas

In [32]:
num_cols = ['trailer_number', 'model_year']

print("--- Skewness Calculation ---")
print(trailers[num_cols].skew())
print("length_feet: Constant column (All values are 53 feet)")

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = trailers[col].quantile(0.25)
    q3 = trailers[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = trailers[(trailers[col] < lower_bound) | (trailers[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")


trailers['acquisition_date'] = pd.to_datetime(trailers['acquisition_date'])


text_columns = ['trailer_id', 'trailer_type', 'vin', 'status', 'current_location']
for col in text_columns:
    trailers[col] = trailers[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(trailers.dtypes)


save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "trailers.csv")
trailers.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
trailer_number   -0.177724
model_year        0.116495
dtype: float64
length_feet: Constant column (All values are 53 feet)

--- Outliers Detection via IQR ---
trailer_number outliers count: 0
model_year outliers count: 0

--- Final Data Types Verification ---
trailer_id                  object
trailer_number               int64
trailer_type                object
length_feet                  int64
model_year                   int64
vin                         object
acquisition_date    datetime64[ns]
status                      object
current_location            object
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\trailers.csv

**12-trips EDA and cleaning if it needs**

In [31]:
tableEDA(trips)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                85410 non-null  object
 1   load_id                85410 non-null  object
 2   driver_id              83696 non-null  object
 3   truck_id               83738 non-null  object
 4   trailer_id             83730 non-null  object
 5   dispatch_date          85410 non-null  object
 6   actual_distance_miles  85410 non-null  int64
 7   actual_duration_hours  85410 non-null  float64
 8   fuel_gallons_used      85410 non-null  float64
 9   average_mpg            85410 non-null  float64
 10  idle_time_hours        85410 non-null  float64
 11  trip_status            85410 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 7.8+ MB

========================================

=== 2. Null Values Count ===
trip_id                     0
load_id                     0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
trip_status                 0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
             trip_id       load_id driver_id  truck_id trailer_id  \
count          85410         85410     83696     83738      83730
unique         85410         85410       124        92        180
top     TRIP00000001  LOAD00000001  DRV00019  TRK00055   TRL00104
freq               1             1       749       977        514
mean             NaN           NaN       NaN       NaN        NaN
std              NaN           NaN       NaN       NaN        NaN
min              NaN           NaN       NaN       NaN        NaN
25%              NaN           NaN       NaN       NaN        NaN
50%              NaN           NaN       NaN       NaN        NaN
75%              NaN           NaN       NaN       NaN        NaN
max              NaN           NaN       NaN       NaN        NaN

       dispatch_date  actual_distance_miles  actual_duration_hours  \
count          85410           85410.000000           85410.000000
unique          1096                    NaN                    NaN
top       2022-05-18                    NaN                    NaN
freq             108                    NaN                    NaN
mean             NaN            1430.268130              25.014674
std              NaN             801.931973              14.191944
min              NaN              90.000000               1.400000
25%              NaN             717.000000              12.600000
50%              NaN            1297.500000              23.000000
75%              NaN            2147.000000              36.900000
max              NaN            3391.000000              67.800000

        fuel_gallons_used   average_mpg  idle_time_hours trip_status
count        85410.000000  85410.000000     85410.000000       85410
unique                NaN           NaN              NaN           1
top                   NaN           NaN              NaN   Completed
freq                  NaN           NaN              NaN       85410
mean           221.827422      6.501463         7.010783         NaN
std            126.558874      0.578091         2.882488         NaN
min             12.000000      5.500000         2.000000         NaN
25%            111.800000      6.000000         4.500000         NaN
50%            204.500000      6.500000         7.000000         NaN
75%            326.400000      7.000000         9.500000         NaN
max            611.900000      7.500000        12.000000         NaN

========================================

=== 5. First 5 Rows Sample ===
        trip_id       load_id driver_id  truck_id trailer_id dispatch_date  \
0  TRIP00000001  LOAD00000001  DRV00117  TRK00035   TRL00167    2022-01-01
1  TRIP00000002  LOAD00000002  DRV00141  TRK00108   TRL00082    2022-01-01
2  TRIP00000003  LOAD00000003  DRV00032  TRK00031   TRL00138    2022-01-01
3  TRIP00000004  LOAD00000004  DRV00083  TRK00105   TRL00018    2022-01-01
4  TRIP00000005  LOAD00000005  DRV00044  TRK00076   TRL00054    2022-01-01

   actual_distance_miles  actual_duration_hours  fuel_gallons_used  \
0                   1314                   26.2              183.8
1                    515                    8.6               93.6
2                   2509                   45.0              339.1
3                    717                   11.1              110.3
4                   2243                   35.0              328.9

   average_mpg  idle_time_hours trip_status
0         7.15              3.5   Completed
1         5.50              8.3   Completed
2         7.40             12.0   Completed
3         6.50              9.6   Completed
4         6.82             11.6   Completed

In [35]:
num_cols = ['actual_distance_miles', 'actual_duration_hours', 'fuel_gallons_used', 'average_mpg', 'idle_time_hours']

print("--- Skewness Calculation ---")
print(trips[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = trips[col].quantile(0.25)
    q3 = trips[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = trips[(trips[col] < lower_bound) | (trips[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

# Handling missing values in ID columns to protect Power BI relationships and operational metrics
trips['driver_id'] = trips['driver_id'].fillna('Unknown')
trips['truck_id'] = trips['truck_id'].fillna('Unknown')
trips['trailer_id'] = trips['trailer_id'].fillna('Unknown')

# Convert dispatch_date to datetime
trips['dispatch_date'] = pd.to_datetime(trips['dispatch_date'])

# Strip whitespace from text columns
text_columns = ['trip_id', 'load_id', 'driver_id', 'truck_id', 'trailer_id', 'trip_status']
for col in text_columns:
    trips[col] = trips[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(trips.dtypes)

print("\n--- Missing Values Count Verification ---")
print(trips.isna().sum())

save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "trips.csv")
trips.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
actual_distance_miles    0.259306
actual_duration_hours    0.314786
fuel_gallons_used        0.337073
average_mpg             -0.002357
idle_time_hours         -0.005123
dtype: float64

--- Outliers Detection via IQR ---
actual_distance_miles outliers count: 0
actual_duration_hours outliers count: 0
fuel_gallons_used outliers count: 0
average_mpg outliers count: 0
idle_time_hours outliers count: 0

--- Final Data Types Verification ---
trip_id                          object
load_id                          object
driver_id                        object
truck_id                         object
trailer_id                       object
dispatch_date            datetime64[ns]
actual_distance_miles             int64
actual_duration_hours           float64
fuel_gallons_used               float64
average_mpg                     float64
idle_time_hours                 float64
trip_status                      object
dtype: object

--- Missing Values Count Verification ---
trip_id                  0
load_id                  0
driver_id                0
truck_id                 0
trailer_id               0
dispatch_date            0
actual_distance_miles    0
actual_duration_hours    0
fuel_gallons_used        0
average_mpg              0
idle_time_hours          0
trip_status              0
dtype: int64

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\trips.csv

**13-truck_utilization_metrics EDA and cleaning if it needs**

In [33]:
tableEDA(truck_utilization_metrics)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   truck_id            3312 non-null   object
 1   month               3312 non-null   object
 2   trips_completed     3312 non-null   int64
 3   total_miles         3312 non-null   int64
 4   total_revenue       3312 non-null   float64
 5   average_mpg         3312 non-null   float64
 6   maintenance_events  3312 non-null   int64
 7   maintenance_cost    3312 non-null   float64
 8   downtime_hours      3312 non-null   float64
 9   utilization_rate    3312 non-null   float64
dtypes: float64(5), int64(3), object(2)
memory usage: 258.9+ KB

========================================

=== 2. Null Values Count ===
truck_id              0
month                 0
trips_completed       0
total_miles           0
total_revenue         0
average_mpg           0
maintenance_events    0
maintenance_cost      0
downtime_hours        0
utilization_rate      0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
        truck_id       month  trips_completed   total_miles  total_revenue  \
count       3312        3312      3312.000000   3312.000000    3312.000000
unique        92          36              NaN           NaN            NaN
top     TRK00001  2022-01-01              NaN           NaN            NaN
freq          36          92              NaN           NaN            NaN
mean         NaN         NaN        25.283213  36152.230072   77700.561564
std          NaN         NaN         5.097786   8213.091728   17995.268042
min          NaN         NaN        11.000000  12680.000000   27876.180000
25%          NaN         NaN        22.000000  30443.500000   65213.702500
50%          NaN         NaN        25.000000  35758.000000   76607.690000
75%          NaN         NaN        29.000000  41550.750000   89556.515000
max          NaN         NaN        46.000000  71177.000000  144891.100000

        average_mpg  maintenance_events  maintenance_cost  downtime_hours  \
count   3312.000000         3312.000000       3312.000000     3312.000000
unique          NaN                 NaN               NaN             NaN
top             NaN                 NaN               NaN             NaN
freq            NaN                 NaN               NaN             NaN
mean       6.500975            0.673309       1307.187630       16.549577
std        0.115717            0.814494       1835.021274       22.997205
min        6.010000            0.000000          0.000000        0.000000
25%        6.420000            0.000000          0.000000        0.000000
50%        6.500000            0.000000          0.000000        0.000000
75%        6.580000            1.000000       2409.790000       30.200000
max        6.860000            4.000000      10414.660000      152.200000

        utilization_rate
count        3312.000000
unique               NaN
top                  NaN
freq                 NaN
mean            0.830447
std             0.166084
min             0.387000
25%             0.710000
50%             0.833000
75%             0.935000
max             1.484000

========================================

=== 5. First 5 Rows Sample ===
   truck_id       month  trips_completed  total_miles  total_revenue  \
0  TRK00001  2022-01-01               22        39269       84792.02
1  TRK00001  2022-02-01               27        40787       88809.05
2  TRK00001  2022-03-01               34        57422      120453.71
3  TRK00001  2022-04-01               20        34428       73531.28
4  TRK00001  2022-05-01               16        20851       40791.53

   average_mpg  maintenance_events  maintenance_cost  downtime_hours  \
0         6.78                   2           4380.98            63.1
1         6.23                   0              0.00             0.0
2         6.49                   0              0.00             0.0
3         6.50                   2           3548.15            71.8
4         6.38                   1           1969.42            43.9

   utilization_rate
0             0.710
1             0.964
2             1.097
3             0.667
4             0.516

In [36]:
num_cols = ['trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 
            'maintenance_events', 'maintenance_cost', 'downtime_hours', 'utilization_rate']

print("--- Skewness Calculation ---")
print(truck_utilization_metrics[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = truck_utilization_metrics[col].quantile(0.25)
    q3 = truck_utilization_metrics[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = truck_utilization_metrics[(truck_utilization_metrics[col] < lower_bound) | (truck_utilization_metrics[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

# Convert month column to datetime for proper Power BI time-intelligence modeling
truck_utilization_metrics['month'] = pd.to_datetime(truck_utilization_metrics['month'])

# Strip text columns
truck_utilization_metrics['truck_id'] = truck_utilization_metrics['truck_id'].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(truck_utilization_metrics.dtypes)

print("\n--- Missing Values Count Verification ---")
print(truck_utilization_metrics.isna().sum())

# Save the cleaned table
save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "truck_utilization_metrics.csv")
truck_utilization_metrics.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
trips_completed       0.243689
total_miles           0.244794
total_revenue         0.257213
average_mpg          -0.099498
maintenance_events    1.146677
maintenance_cost      1.496932
downtime_hours        1.538906
utilization_rate      0.236572
dtype: float64

--- Outliers Detection via IQR ---
trips_completed outliers count: 17
total_miles outliers count: 19
total_revenue outliers count: 18
average_mpg outliers count: 15
maintenance_events outliers count: 108
maintenance_cost outliers count: 105
downtime_hours outliers count: 92
utilization_rate outliers count: 19

--- Final Data Types Verification ---
truck_id                      object
month                 datetime64[ns]
trips_completed                int64
total_miles                    int64
total_revenue                float64
average_mpg                  float64
maintenance_events             int64
maintenance_cost             float64
downtime_hours               float64
utilization_rate             float64
dtype: object

--- Missing Values Count Verification ---
truck_id              0
month                 0
trips_completed       0
total_miles           0
total_revenue         0
average_mpg           0
maintenance_events    0
maintenance_cost      0
downtime_hours        0
utilization_rate      0
dtype: int64

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\truck_utilization_metrics.csv

**14-trucks EDA and cleaning if it needs**

In [34]:
tableEDA(trucks)

=== 1. Table Info and Data Types ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    object
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    object
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    object
 5   acquisition_date       120 non-null    object
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    object
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    object
 10  home_terminal          120 non-null    object
dtypes: int64(4), object(7)
memory usage: 10.4+ KB

========================================

=== 2. Null Values Count ===
truck_id                 0
unit_number              0
make                     0
model_year               0
vin                      0
acquisition_date         0
acquisition_mileage      0
fuel_type                0
tank_capacity_gallons    0
status                   0
home_terminal            0
dtype: int64

========================================

=== 3. Total Duplicated Rows ===
Total Duplicates: 0

========================================

=== 4. Descriptive Statistics ===
        truck_id  unit_number       make   model_year                 vin  \
count        120   120.000000        120   120.000000                 120
unique       120          NaN          6          NaN                 120
top     TRK00001          NaN  Peterbilt          NaN  1VV205190335317039
freq           1          NaN         24          NaN                   1
mean         NaN  5568.641667        NaN  2015.891667                 NaN
std          NaN  2563.782076        NaN     1.448243                 NaN
min          NaN  1086.000000        NaN  2015.000000                 NaN
25%          NaN  3306.000000        NaN  2015.000000                 NaN
50%          NaN  5669.000000        NaN  2015.000000                 NaN
75%          NaN  7812.500000        NaN  2017.000000                 NaN
max          NaN  9991.000000        NaN  2021.000000                 NaN

       acquisition_date  acquisition_mileage fuel_type  tank_capacity_gallons  \
count               120           120.000000       120             120.000000
unique              119                  NaN         1                    NaN
top          2016-02-16                  NaN    Diesel                    NaN
freq                  2                  NaN       120                    NaN
mean                NaN         26058.216667       NaN             201.666667
std                 NaN         14373.443614       NaN              39.922895
min                 NaN           227.000000       NaN             150.000000
25%                 NaN         14567.000000       NaN             150.000000
50%                 NaN         26060.500000       NaN             200.000000
75%                 NaN         38812.250000       NaN             250.000000
max                 NaN         49556.000000       NaN             250.000000

        status home_terminal
count      120           120
unique       3            24
top     Active        Dallas
freq        92            10
mean       NaN           NaN
std        NaN           NaN
min        NaN           NaN
25%        NaN           NaN
50%        NaN           NaN
75%        NaN           NaN
max        NaN           NaN

========================================

=== 5. First 5 Rows Sample ===
   truck_id  unit_number          make  model_year                 vin  \
0  TRK00001         3463     Peterbilt        2016  1VV205190335317039
1  TRK00002         6461      Kenworth        2015  1NV753749606229960
2  TRK00003         2335     Peterbilt        2018  1NT803101860493229
3  TRK00004         3317  Freightliner        2015  1VV131945381692351
4  TRK00005         6731  Freightliner        2016  1FT822215709701985

  acquisition_date  acquisition_mileage fuel_type  tank_capacity_gallons  \
0       2017-04-27                18814    Diesel                    200
1       2018-10-04                26795    Diesel                    150
2       2020-09-17                11795    Diesel                    150
3       2017-06-17                 8875    Diesel                    200
4       2021-10-08                42042    Diesel                    250

        status   home_terminal
0       Active           Omaha
1       Active         Seattle
2  Maintenance         Atlanta
3       Active  Salt Lake City
4  Maintenance           Miami

In [37]:
num_cols = ['unit_number', 'model_year', 'acquisition_mileage', 'tank_capacity_gallons']

print("--- Skewness Calculation ---")
print(trucks[num_cols].skew())

print("\n--- Outliers Detection via IQR ---")
for col in num_cols:
    q1 = trucks[col].quantile(0.25)
    q3 = trucks[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = trucks[(trucks[col] < lower_bound) | (trucks[col] > upper_bound)]
    print(f"{col} outliers count: {len(outliers)}")

# Convert acquisition_date to datetime
trucks['acquisition_date'] = pd.to_datetime(trucks['acquisition_date'])

# Strip spaces from text columns
text_columns = ['truck_id', 'make', 'vin', 'status', 'home_terminal']
for col in text_columns:
    trucks[col] = trucks[col].astype(str).str.strip()

print("\n--- Final Data Types Verification ---")
print(trucks.dtypes)

# Save the final cleaned table
save_path = r"C:\Users\pc\Desktop\DEPI\final project\data cleaned"
os.makedirs(save_path, exist_ok=True)
final_file_path = os.path.join(save_path, "trucks.csv")
trucks.to_csv(final_file_path, index=False)
print("\n--- Table Saved Successfully to:", final_file_path)

--- Skewness Calculation ---
unit_number              0.027480
model_year               1.559369
acquisition_mileage     -0.045012
tank_capacity_gallons   -0.060287
dtype: float64

--- Outliers Detection via IQR ---
unit_number outliers count: 0
model_year outliers count: 1
acquisition_mileage outliers count: 0
tank_capacity_gallons outliers count: 0

--- Final Data Types Verification ---
truck_id                         object
unit_number                       int64
make                             object
model_year                        int64
vin                              object
acquisition_date         datetime64[ns]
acquisition_mileage               int64
fuel_type                        object
tank_capacity_gallons             int64
status                           object
home_terminal                    object
dtype: object

--- Table Saved Successfully to: C:\Users\pc\Desktop\DEPI\final project\data cleaned\trucks.csv